repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        name: ruff check --fix
        language_version: python3
        types: [python]
        files: ^src/
      - id: ruff-format
        name: ruff format
        language_version: python3
        types: [python]
        files: ^src/