apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nim-llm
spec:
  image:
    repository: nvcr.io/nim/nvidia/llama-3.3-nemotron-super-49b-v1
    tag: 1.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: nemotron-llama3-49b-super
      profile: ''
  replicas: 1
  resources:
    limits:
# Change the GPU count from 2 to 4 for A100 80GB 
      nvidia.com/gpu: 2
    requests:
      nvidia.com/gpu: 2
  expose:
    service:
      type: ClusterIP
      port: 8000
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemoretriever-page-elements-v2
spec:
  image:
    repository: nvcr.io/nim/nvidia/nemoretriever-page-elements-v2
    tag: 1.4.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: nemoretriever-page-elements-v2
      profile: ''
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      name: http
      type: ClusterIP
      port: 8000
      grpcPort: 8001
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemoretriever-graphic-elements-v1
spec:
  image:
    repository: nvcr.io/nim/nvidia/nemoretriever-graphic-elements-v1
    tag: 1.4.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: nemoretriever-graphic-elements-v1
      profile: ''
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      name: http
      type: ClusterIP
      port: 8000
      grpcPort: 8001
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemoretriever-table-structure-v1
spec:
  image:
    repository: nvcr.io/nim/nvidia/nemoretriever-table-structure-v1
    tag: 1.4.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: nemoretriever-table-structure-v1
      profile: ''
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      name: http
      type: ClusterIP
      port: 8000
      grpcPort: 8001
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemo-retriever-embedding-ms
spec:
  image:
    repository: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2
    tag: 1.9.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: nvidia-nim-llama-32-nv-embedqa-1b-v2
      profile: ''
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      type: ClusterIP
      port: 8000
      grpcPort: 8001
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemo-retriever-reranking-ms
spec:
  image:
    repository: nvcr.io/nim/nvidia/llama-3.2-nv-rerankqa-1b-v2
    tag: 1.7.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: nvidia-nim-llama-32-nv-rerankqa-1b-v2
      profile: ''
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      type: ClusterIP
      port: 8000
      grpcPort: 8001